# Generated by Django 6.0.7 on 2026-10-01 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_eventregistration_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="eventregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("NEW", "PENDING_PAYMENT", "CONFIRMED"))
                ),
                fields=("event", "phone"),
                name="uq_event_registration_active_phone",
            ),
        ),
    ]
