# Generated by Django 6.0.6 on 2026-07-12 15:51

import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', verbose_name='Телефон')),
                ('preferred_time_window', models.CharField(choices=[('MORNING', 'Утро (9:00–12:00)'), ('AFTERNOON', 'День (12:00–17:00)'), ('EVENING', 'Вечер (17:00–21:00)')], max_length=20, verbose_name='Удобное время звонка')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Обработана'), ('SPAM', 'Спам')], db_index=True, default='NEW', max_length=20, verbose_name='Статус обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Заявка на обратный звонок',
                'verbose_name_plural': 'Заявки на обратный звонок',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('NEW', 'Новое'), ('REVIEWED', 'Рассмотрено'), ('SPAM', 'Спам')], db_index=True, default='NEW', max_length=20, verbose_name='Статус обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Обращение с сайта',
                'verbose_name_plural': 'Обращения с сайта',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalCallbackRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region='RU', verbose_name='Телефон')),
                ('preferred_time_window', models.CharField(choices=[('MORNING', 'Утро (9:00–12:00)'), ('AFTERNOON', 'День (12:00–17:00)'), ('EVENING', 'Вечер (17:00–21:00)')], max_length=20, verbose_name='Удобное время звонка')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('DONE', 'Обработана'), ('SPAM', 'Спам')], db_index=True, default='NEW', max_length=20, verbose_name='Статус обработки')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Обновлена')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Заявка на обратный звонок',
                'verbose_name_plural': 'historical Заявки на обратный звонок',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFeedbackRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('NEW', 'Новое'), ('REVIEWED', 'Рассмотрено'), ('SPAM', 'Спам')], db_index=True, default='NEW', max_length=20, verbose_name='Статус обработки')),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Создано')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Обращение с сайта',
                'verbose_name_plural': 'historical Обращения с сайта',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
