# Generated by Django 6.0.6 on 2026-07-09 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
        ("schedule", "0003_schedule_sync_triggers"),
        ("users", "0002_teacherprofile"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="enrollment",
            name="uq_billing_active_enrollment_per_student_slot",
        ),
        migrations.AddField(
            model_name="enrollment",
            name="schedule",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrollment",
                to="schedule.schedule",
                verbose_name="Группа",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="enrollment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ("HELD", "ENROLLED"))),
                fields=("student", "schedule"),
                name="uq_billing_active_enrollment_per_student_slot",
            ),
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="slot_id",
        ),
    ]
