# Generated by Django 6.0.7 on 2026-09-29 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0010_transaction_refund_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_recheck_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Досверить платёж до"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                condition=models.Q(("payment_recheck_until__isnull", False)),
                fields=["payment_recheck_until"],
                name="ix_billing_tx_payment_recheck",
            ),
        ),
    ]
