# Generated by Django 6.0.7 on 2026-10-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0011_transaction_payment_recheck_until"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="subscriptionplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("slots_count__gte", 1)),
                name="ck_billing_plan_slots_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplan",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_session_price__gte", 0), ("price__gte", 0)),
                name="ck_billing_plan_prices_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_unlimited", False)),
                fields=("slots_count",),
                name="uq_billing_active_plan_per_slots_count",
                violation_error_message="Активный тариф на это число слотов уже есть — сначала снимите его с продажи.",
            ),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_unlimited", True)),
                fields=("is_unlimited",),
                name="uq_billing_single_active_unlimited_plan",
                violation_error_message="Активный безлимит уже есть — сначала снимите его с продажи.",
            ),
        ),
    ]
