# Generated by Django 6.0.7 on 2026-10-05 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0012_subscription_plan_constraints"),
        ("events", "0005_eventregistration_amount_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="event_registration",
            field=models.ForeignKey(
                blank=True,
                db_index=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="events.eventregistration",
                verbose_name="Бронь события",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Родитель",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("enrollment__isnull", True),
                        ("event_registration__isnull", True),
                        ("parent__isnull", False),
                        ("subscription__isnull", False),
                    ),
                    models.Q(
                        ("enrollment__isnull", False),
                        ("event_registration__isnull", True),
                        ("parent__isnull", False),
                        ("subscription__isnull", True),
                    ),
                    models.Q(
                        ("enrollment__isnull", True),
                        ("event_registration__isnull", False),
                        ("subscription__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="ck_billing_tx_single_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_registration__isnull", False)),
                fields=("event_registration",),
                name="uq_billing_tx_per_event_registration",
            ),
        ),
    ]
