# Generated by Django 6.0.7 on 2026-10-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0013_transaction_event_registration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="base_session_price",
            field=models.IntegerField(verbose_name="Базовая цена занятия"),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="price",
            field=models.IntegerField(verbose_name="Цена"),
        ),
    ]
