# Generated by Django 6.0.7 on 2026-09-25 16:10
#
# ПОЧЕМУ без заполнения данных (в отличие от 0005): согласие на обработку ПД
# нельзя «проставить задним числом» — это подделка доказательства (152-ФЗ).
# Все, кто зарегистрировался до этой миграции, при следующем входе увидят
# анкету с одной галочкой согласия. Nullable-колонка и новая таблица не
# переписывают users_parent; откат удаляет обе.

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_parent_referral_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="pd_consent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Согласие на обработку ПД"
            ),
        ),
        migrations.CreateModel(
            name="PersonalDataConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("REGISTRATION", "Регистрация в личном кабинете"),
                            ("CALLBACK", "Заказ обратного звонка"),
                            ("FEEDBACK", "Обратная связь"),
                            ("EVENT_REGISTRATION", "Запись на событие"),
                        ],
                        max_length=32,
                        verbose_name="Где дано",
                    ),
                ),
                (
                    "document_version",
                    models.CharField(max_length=32, verbose_name="Версия документа"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region="RU", verbose_name="Телефон"
                    ),
                ),
                (
                    "source_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="ID заявки"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Браузер"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дано"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_index=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pd_consents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Родитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Согласие на обработку ПД",
                "verbose_name_plural": "Согласия на обработку ПД",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["parent", "-created_at"], name="pdc_parent_created_idx"
                    ),
                    models.Index(
                        fields=["purpose", "source_id"], name="pdc_purpose_source_idx"
                    ),
                ],
            },
        ),
    ]
