# Generated by Django 6.0.6 on 2026-07-07 11:55

import apps.schedule.models
import django.contrib.postgres.constraints
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("schedule", "0001_enable_btree_gist"),
        ("users", "0002_teacherprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
            ],
            options={
                "verbose_name": "Кабинет",
                "verbose_name_plural": "Кабинеты",
                "db_table": "room",
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        verbose_name="День недели",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Начало")),
                ("end_time", models.TimeField(verbose_name="Окончание")),
            ],
            options={
                "verbose_name": "Временной слот",
                "verbose_name_plural": "Временные слоты",
                "db_table": "time_slot",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="time_slot_end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("day_of_week__gte", 0), ("day_of_week__lte", 6)
                        ),
                        name="time_slot_day_of_week_in_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название группы"
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveSmallIntegerField(
                        default=6, verbose_name="Максимум детей"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "day_of_week",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        editable=False,
                        verbose_name="День недели (денорм.)",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(editable=False, verbose_name="Начало (денорм.)"),
                ),
                (
                    "end_time",
                    models.TimeField(
                        editable=False, verbose_name="Окончание (денорм.)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="slots",
                        to="catalog.activity",
                        verbose_name="Кружок",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="schedule.room",
                        verbose_name="Кабинет",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedules",
                        to="users.teacherprofile",
                        verbose_name="Преподаватель",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedules",
                        to="schedule.timeslot",
                        verbose_name="Слот",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа расписания",
                "verbose_name_plural": "Группы расписания",
                "db_table": "schedule",
            },
        ),
        migrations.CreateModel(
            name="ScheduleMask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_date",
                    models.DateField(db_index=True, verbose_name="Дата занятия"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("CANCELLATION", "Отмена"), ("RESCHEDULE", "Перенос")],
                        max_length=20,
                        verbose_name="Тип маски",
                    ),
                ),
                (
                    "new_day_of_week",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[
                            (0, "Понедельник"),
                            (1, "Вторник"),
                            (2, "Среда"),
                            (3, "Четверг"),
                            (4, "Пятница"),
                            (5, "Суббота"),
                            (6, "Воскресенье"),
                        ],
                        null=True,
                        verbose_name="Новый день недели",
                    ),
                ),
                (
                    "new_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Новое начало"
                    ),
                ),
                (
                    "new_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Новое окончание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "new_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="schedule.room",
                        verbose_name="Новый кабинет",
                    ),
                ),
                (
                    "new_teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="users.teacherprofile",
                        verbose_name="Новый преподаватель",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masks",
                        to="schedule.schedule",
                        verbose_name="Группа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Маска расписания",
                "verbose_name_plural": "Маски расписания",
                "db_table": "schedule_mask",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("schedule", "target_date"),
                        name="uniq_mask_per_schedule_per_date",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("new_day_of_week__isnull", True),
                            models.Q(
                                ("new_day_of_week__gte", 0), ("new_day_of_week__lte", 6)
                            ),
                            _connector="OR",
                        ),
                        name="schedule_mask_new_day_in_range",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_time__gt", models.F("start_time"))),
                name="schedule_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("day_of_week__gte", 0), ("day_of_week__lte", 6)),
                name="schedule_day_of_week_in_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("is_active", True), ("teacher__isnull", False)),
                expressions=[
                    (models.F("teacher"), "="),
                    (models.F("day_of_week"), "="),
                    (
                        apps.schedule.models.TimeOfDayRange("start_time", "end_time"),
                        "&&",
                    ),
                ],
                name="no_teacher_time_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("is_active", True), ("room__isnull", False)),
                expressions=[
                    (models.F("room"), "="),
                    (models.F("day_of_week"), "="),
                    (
                        apps.schedule.models.TimeOfDayRange("start_time", "end_time"),
                        "&&",
                    ),
                ],
                name="no_room_time_overlap",
            ),
        ),
    ]
