# Generated by Django 6.0.7 on 2026-10-08 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0004_schedule_age_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="day_of_week",
            field=models.SmallIntegerField(
                choices=[
                    (0, "Понедельник"),
                    (1, "Вторник"),
                    (2, "Среда"),
                    (3, "Четверг"),
                    (4, "Пятница"),
                    (5, "Суббота"),
                    (6, "Воскресенье"),
                ],
                editable=False,
                verbose_name="День недели",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="end_time",
            field=models.TimeField(editable=False, verbose_name="Окончание"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_time",
            field=models.TimeField(editable=False, verbose_name="Начало"),
        ),
    ]
