# Generated by Django 6.0.7 on 2026-10-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "schedule",
            "0005_alter_schedule_day_of_week_alter_schedule_end_time_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedulemask",
            options={
                "verbose_name": "Перенос или отмена",
                "verbose_name_plural": "Переносы и отмены",
            },
        ),
        migrations.AlterField(
            model_name="schedulemask",
            name="type",
            field=models.CharField(
                choices=[("CANCELLATION", "Отмена"), ("RESCHEDULE", "Перенос")],
                max_length=20,
                verbose_name="Отмена или перенос",
            ),
        ),
    ]
