# Generated by Django 6.0.7 on 2026-10-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_activity_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"verbose_name": "Кружок", "verbose_name_plural": "Кружки"},
        ),
        migrations.AlterField(
            model_name="activity",
            name="category",
            field=models.CharField(
                choices=[("CLUB", "Кружок"), ("SERVICE", "Услуга")],
                default="CLUB",
                max_length=50,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Адрес в ссылке"),
        ),
    ]
